language: java

jdk: oraclejdk8
before_install:
- chmod +x gradlew
script: 
- ./gradlew clean assembleDebug
install:
 - true
 - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
android: 
 components: 
    - build-tools-24.0.1
    - android-24
env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}

