language: java

jdk: oraclejdk8
before_install:
- chmod +x gradlew
script: 
- ./gradlew clean assembleDebug
install:
 - true
 - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
android: 
 components: 
    - build-tools-24.0.1
    - android-24

